'use strict';

module.exports =
  angular.module('MeowChater', [
    'ui.bootstrap',
    'ui.router',
    //load extra external dependencies here, e.g.:
    //'ngAnimate',
    //html templates in $templateCache generated by Gulp:
    require('../../../tmp/templates').name,
    //useful directives, filters, services shared across the app
    require('../common').name,
    // app module:
      require('./account').name,
      require('./chat_room').name

  ])
      .controller('Main',function ($scope, $state,sessionService) {
          $scope.start = function () {
              if(sessionService.isLogin()){
                  $state.go('chat');
              }else {
                  $state.go('login');
              }
          }
      });
;
